image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - master
  #  tags:
  #    - k8
  script: "./gradlew build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:

  stage: package
  #  tags:
  #    - k8
  only:
    - master

  script:

    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

deploy-master:

  stage: deploy

  image: mateothegreat/docker-alpine-gcloud-kubectl

  only:

    - master

  variables:

    MYSQL_HOST: "$PROD_MYSQL_HOST"
    MYSQL_USER: "$PROD_MYSQL_USER"
    MYSQL_PASS: "$PROD_MYSQL_PASS"
    MYSQL_DATABASE: "ideationworks"

  script:

    - kubectl config set-cluster kube-cluster --server="$K8_PROD_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab --token="$K8_PROD_TOKEN"
    - kubectl config set-context default-context --cluster=kube-cluster --user=gitlab
    - kubectl config use-context default-context
    - apk --update add git
    - git submodule update --init
    - make install
