server:
  port: 18080

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      max-page-size: 2147483647
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect:    org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:             jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ideationworks}?allowPublicKeyRetrieval=true&reconnect=true&verifyServerCertificate=false&useSSL=false&useUnicode=true&character_set_client=utf8mb4&character_set_server=utf8mb4
    username:        ${MYSQL_USER:root}
    password:        ${MYSQL_PASS:mysql}
  jackson:
    serialization:
      fail-on-empty-beans:       false
      WRITE_DATES_AS_TIMESTAMPS: false


